/* 
What is a magnitude Analysis? It is all about comparing our measure values across different categories and dimensions. And this is going to help us to the importance of different categories of our business. 
Here we will be calculating our measure by Dimension 
We will be analyzing 7 things here
1.	Find the total customers by country
2.	Find the total customers by gender
3.	Find total products by category
4.	What are the average costs in each category?
5.	What is the total revenue generated for each category?
6.	Find total revenue generated by each customer
7.	What is the distribution of sold items across countries?
*/


--1.	Find the total customers by country
SELECT 
        country,
        COUNT(customer_key) AS total_customer
FROM    gold.dim_customers
GROUP BY 
        country
ORDER BY
        total_customer DESC


--2.	Find the total customers by gender
SELECT 
        gender,
        COUNT(customer_key) AS customer_gender
FROM    gold.dim_customers
GROUP BY 
        gender


--3.	Find total products by category
SELECT 
        category,
        COUNT(product_key) AS total_products
FROM    gold.dim_products
GROUP BY 
        category
order by    
        total_products DESC


-- 4.	What are the average costs in each category?
SELECT 
        category,
        ROUND (AVG (cost), 2) AS AVG_cost
FROM    gold.dim_products
WHERE   category is not NULL
GROUP BY 
        category
order by    
        AVG_cost DESC


-- 5.   What is the total revenue generated for each category?
            -- Here the total revenue comes from the sales table 
            -- and category comes from produts so we will join table

SELECT 
            p.category,
            SUM (s.sales_amount) total_revenue
FROM        gold.fact_sales s
LEFT join   gold.dim_products p
ON          p.product_key = s.product_key
GROUP BY    P.category
ORDER BY    total_revenue DESC


--6.	Find total revenue generated by our Top 10 customer
SELECT 
            c.customer_key,
            c.first_name,
            c.last_name,
           SUM (s.sales_amount) As total_revenue
FROM 
            gold.fact_sales s
LEFT join   gold.dim_customers c
ON c.customer_key = s.customer_key
GROUP BY
            c.customer_key,
            c.first_name,
            c.last_name
ORDER BY    total_revenue DESC
LIMIT 10


-- 7.   What is the distribution of sold items across countries?

SELECT 
            c.country,
           SUM (s.quantity) As total_sold_items
FROM 
            gold.fact_sales s
LEFT join   gold.dim_customers c
ON c.customer_key = s.customer_key
GROUP BY
            c.country
ORDER BY    total_sold_items DESC

